server:
  port: 8810

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission
    username: root
    password: zhanghy0330
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: permission-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos的ip和端口
        group: tony-group
management:
endpoints:
  web:
    exposure:
      include: '*'
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# knife4j 配置
knife4j:
  enable: true
  #  production: true # 仅在处于生产环境时开启
  openapi:
    title: 权限服务
    description: "权限服务"
    email: xiaoyu208h@qq.com
    concat: xiaoyu
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: permissionPort
        api-rule: package
        api-rule-resources:
          - edu.zut.controller