server:
  port: 8809

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logging
    username: root
    password: zhanghy0330
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: logging-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos的ip和端口
        group: tony-group
management:
endpoints:
  web:
    exposure:
      include: '*'
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.context.support: debug
